### ISSUE TITLE
Publishing `.idea` folder to npm

### ISSUE THREAD

**Issue by danielpa9708** [williamkapke/bson-objectid#15]
The `.idea` folder (webstorm generated I think) is been pushed to npm, please put it in the gitignore.
Great package btw.

```
$ ls -a
.  ..  .editorconfig  .idea  LICENSE  .npmignore  objectid.d.ts  objectid.js  package.json  README.md  test  typing-tests
```

**Comment by williamkapke** [comment]
The NPM cli wasn't respecting the global gitignore at the time of my last push :(
I [added it to the project level .gitignore](https://github.com/williamkapke/bson-objectid/commit/161c8294499c9b286fcd63be9f4fc10a56d299ca) and republished @1.2.2
