### ISSUE TITLE
Typescript errors

### ISSUE THREAD

**Issue by tobi-or-not** [williamkapke/bson-objectid#19]
Hi,

I pulled the npm package (version 1.2.3) into an Angular 5 project, using typescript. When I try to build the project I get two errors:

``
ERROR in node_modules/bson-objectid/objectid.d.ts(20,25): error TS2304: Cannot find name 'Buffer'.
``

``
src/app/term.service.ts(7,10): error TS2305: Module '"<path>/node_modules/bson-objectid/objectid"' has no exported member 'ObjectID'.
``

Does anyone know why this might happen and how to solve that problem?

**Comment by wendellmva** [comment]
@williamkapke @tobi-or-not Node has refactored Buffer into it's own namespace so, in the objectid.d.ts file of the package this must be included for this error to go away 'import {Buffer} from 'buffer'; since buffer is now orphaned it that file.

**Comment by williamkapke** [comment]
This should be fixed by #20 now? Please reopen if not.

Thanks!

**Comment by stherrienaspnet** [comment]
I'm facing the same issue, is it suposed to be fixed in the current version?
