### ISSUE TITLE
Cannot get version 1.2.4 from npm

### ISSUE THREAD

**Issue by stherrienaspnet** [williamkapke/bson-objectid#21]
No matching version found for bson-objectid 1.2.4

I was hopping this could fix the issue with typescript and buffer reference.

Thanks

**Comment by williamkapke** [comment]
published now!

I was holding off until someone confirmed that it fixed the problem. I'm not a TS person- so I wasn't sure. (Still not sure)

**Comment by stherrienaspnet** [comment]
I have loaded your package from master. I see your change but something else missing. I will debug it and let you known about the minor changes to do.
