### ISSUE TITLE
ObjectID.isValid should check that `typeof toString === 'function'` otherwise if it's not an object and doesn't have a `toString` then it would return false

### ISSUE THREAD

**Issue by niftylettuce** [williamkapke/bson-objectid#27]

**Comment by niftylettuce** [comment]
e.g. if you pass an empty plain object to `ObjectID.isValid` it throws an uncaught exception.

**Comment by niftylettuce** [comment]
Specifically https://github.com/williamkapke/bson-objectid/blob/master/objectid.js#L98 should change to `if (!objectid || (typeof objectid !== 'string' && (typeof objectid !== 'object' || typeof objectid.toString !== 'function'))`

**Comment by williamkapke** [comment]
seems right. I'm happy to take a PR for it!

**Comment by niftylettuce** [comment]
roger, PR inbound

**Comment by niftylettuce** [comment]
@williamkapke 	see #28, I also added a test case as well.

let me know of any issues, or when a new version is published to npm.

thanks many! 👍
