### ISSUE TITLE
No changelog

### ISSUE THREAD

**Issue by connorjburton** [williamkapke/bson-objectid#29]
There is no change log associated with this project.

https://keepachangelog.com/en/1.0.0/

**Comment by niftylettuce** [comment]
Read commit log for now, please close this.

For future released, @williamkapke please use `np` package.

https://github.com/sindresorhus/np

If you use `np`, then once the version is package/tagged/pushed to GitHub (automatically), a page will open to GitHub releases with a draft release, which you can then use as the Changelog (the GitHub releases tab).  I use this across all my projects to manage changelog.

**Comment by niftylettuce** [comment]
Thanks to @williamkapke I can now contribute here and on npm.  See the Releases <https://github.com/williamkapke/bson-objectid/releases tab moving forwards, I'm about to publish an update here and there will be a new release there.
