### ISSUE TITLE
Typescript import issue

### ISSUE THREAD

**Issue by lukszymanski** [williamkapke/bson-objectid#36]
Hi there,
keep getting 
`Value of type 'typeof ObjectID' is not callable` error with Typescript

snippet
```
import ObjectID from 'bson-objectid';

const value = 'object-id-string';
const id = ObjectID(value);
```

package.json
```
"typescript": "~4.0.5"
    "bson-objectid": "^1.3.1",
```

Ignoring ts lint check will do the trick but still kind'a strange.
Anyone had some problems with that?

**Comment by MumblesNZ** [comment]
Looking at the type definitions ObjectId is a class. Try 

        import ObjectID from 'bson-objectid';
        
        const value = 'object-id-string';
        const id = new ObjectID(value);

Note, object-id-string needs to be a string of 12 bytes or 24 hex characters.

**Comment by niftylettuce** [comment]
v2.0.0 released
