### ISSUE TITLE
Types have not been updated and ObjectId.generate is no longer being exported

### ISSUE THREAD

**Issue by supersolidKate** [williamkapke/bson-objectid#38]
In objectid.d.ts the comment shows the types are still for 1.3.1

```
// Type definitions for bson-objectid 1.3.1
```

`ObjectID.generate = generate` has been removed but the types are not updated.

Get error

```
TypeError: bson_objectid_1.default.generate is not a function
```

**Comment by niftylettuce** [comment]
PR welcome

**Comment by johnbonds** [comment]
In case anyone is wondering how to get a MongoDb-style id string using this library

import ObjectID from 'bson-objectid';
new ObjectID().toHexString();
