### ISSUE TITLE
pid is NaN when used with browserify

### ISSUE THREAD

**Issue by rahatarmanahmed** [williamkapke/bson-objectid#4]
I'm using this module with browserify and `ObjectId.generate()` is returning strings like `565c8e5032d34b0NaNa0ad07`. Found that this is because when [this line](https://github.com/williamkapke/bson-objectid/blob/c19e61045345de330d826f43498fadabe7557ab4/objectid.js#L4) executes on the browser, `process` exists but `process.pid` does not.

A workaround is to use `new ObjectId().toString()`, which generates a correct id.

**Comment by williamkapke** [comment]
How strange. Since `ObjectId().toString()` uses `generate()` I would thing you would still see the issue. 

Anyhow, it's easy enough to check and make sure that `porcess.pid` is there :)

Thanks for the PR!

**Comment by rahatarmanahmed** [comment]
No problem! Yeah, I'm not sure why only `generate()` was broken, I didn't look too far into it.

If it's not too much trouble, could you publish this fix to npm in a new version?

**Comment by williamkapke** [comment]
1.1.2 published :+1:

**Comment by rahatarmanahmed** [comment]
Thanks!
