### ISSUE TITLE
Api is not matching the one from `bson` - `getTimestamp` 

### ISSUE THREAD

**Issue by dawidreedsy** [williamkapke/bson-objectid#43]
`getTimestamp` should return the `Date` at the moment is returning the `number`

**Comment by niftylettuce** [comment]
Can you submit a PR to fix this?

**Comment by MrEmanuel** [comment]
It's actually returning `Date` as of now, but is typed to return `number`. I'll make a quick PR to fix it. :)

**Comment by niftylettuce** [comment]
The PR #46 broke all tests.  I am going to revert it in the interim.

I also noticed we need to merge this https://github.com/418sec/bson-objectid/pull/2.

**Comment by niftylettuce** [comment]
This should be fixed now in v2.0.3
