### ISSUE TITLE
ObjectID sometimes generates 26 characters

### ISSUE THREAD

**Issue by rahatarmanahmed** [williamkapke/bson-objectid#6]
Using bson-objectid with browserify, occasionally `ObjectID.generate()` generates a 26 character id (and `new ObjectID.toString()` returns a blank string).

I suspect it happens because the pid for browsers is [set to a random number](https://github.com/williamkapke/bson-objectid/blob/df890be4f4d5714136f1261aa215853ed09178ab/objectid.js#L4) between 0 and 100000. It seems to happen when the generated pid is > 0xFFFF (ex: once when this occurred, pid was set to 81783)

**Comment by williamkapke** [comment]
Gah! I only applied the `% 0xFFFF` to `process.pid` :(

We just need to wrap in parens so it applies to both:
```javascript
var pid = (typeof process === 'undefined' || typeof process.pid !== 'number' ? Math.floor(Math.random() * 10000) : process.pid) % 0xFFFF;
```

Can submit a PR with that instead?

**Comment by rahatarmanahmed** [comment]
Done!

**Comment by williamkapke** [comment]
AAAnnnd published :)

BTW, I got that `% 0xFFFF` merged into the `bson` lib a while back & it has this same issue.

See: https://github.com/mongodb/js-bson/issues/104

You can fix it over there too if you want!

Thanks again.
